In [1]:
from sklearn.datasets import fetch_openml
import numpy as np
mnist = fetch_openml('mnist_784', version=1, as_frame=False)
mnist.target = mnist.target.astype(np.uint8)
X = mnist["data"]
y = mnist["target"]

In [2]:
from sklearn.cluster import KMeans 
from sklearn.metrics import silhouette_score

In [3]:
lista =[]
for k in range(8,13):
    kmeans = KMeans(n_clusters=k, random_state=42)
    y_pred = kmeans.fit_predict(X)
    lista.append(silhouette_score(X, kmeans.labels_))
    print(silhouette_score(X, kmeans.labels_))

0.07338401965925966
0.05683381826333592
0.05869201052848778
0.05836351154790604
0.05894738457992754


In [4]:
import pickle
file = open("kmeans_sil.pkl","wb")
pickle.dump(lista, file)

In [5]:
file = open("kmeans_sil.pkl","rb")
a = pickle.load(file)
file.close()
print(a)

[0.07338401965925966, 0.05683381826333592, 0.05869201052848778, 0.05836351154790604, 0.05894738457992754]


In [6]:
kmeans = KMeans(n_clusters=10, random_state=42)
y_pred = kmeans.fit_predict(X)

In [7]:
kmeans.labels_

array([8, 9, 3, ..., 5, 2, 6])

In [8]:
from sklearn.metrics import confusion_matrix
cf = confusion_matrix(y, y_pred)
print(cf)

[[ 290    2 1265   39    9    7  162    4   72 5053]
 [   8 4293    7    7   10   11    7 3526    8    0]
 [ 323  423  246  216 4863   78  147  436  201   57]
 [4581  449  461  193  216   45   31   58 1083   24]
 [   0  178  288 3728   29 2173  168  234   17    9]
 [2129  155 1812  432    7  215   67  280 1156   60]
 [  38  190 2068   67   53    4 4326   45   14   71]
 [   6  372   12 2094   53 4399    4  314   18   21]
 [1212  335  292  208   53  193   51  330 4115   36]
 [  87  261   31 3462   19 2849   16   95   87   51]]


In [9]:
print(y_pred)
print(y)

[8 9 3 ... 5 2 6]
[5 0 4 ... 4 5 6]


In [10]:
lista2 = []
for i in cf:
    lista2.append(i[i.argmax()])
lista2 = list(set(lista2))
lista2.sort(reverse=True)

In [11]:
print(lista2)

[5053, 4863, 4581, 4399, 4326, 4293, 4115, 3728, 3462, 2129]


In [12]:
file = open("kmeans_argmax.pkl","wb")
pickle.dump(lista2, file)

In [13]:
file = open("kmeans_argmax.pkl","rb")
a = pickle.load(file)
file.close()
print(a)

[5053, 4863, 4581, 4399, 4326, 4293, 4115, 3728, 3462, 2129]


In [14]:
from sklearn.cluster import DBSCAN

In [15]:
lista3 = []
lista4 =[]
for i in range(0, 300):
    for j in range(0, 300):
        if i != j:
            lista3.append(np.linalg.norm(X[i]-X[j]))
lista3.sort()
lista4 = lista3[:10]
lista4.sort(reverse = True)

In [16]:
file = open("dist.pkl","wb")
pickle.dump(lista4, file)

In [17]:
file = open("dist.pkl","rb")
a = pickle.load(file)
file.close()
print(a)

[638.4520342202694, 638.4520342202694, 638.289902787127, 638.289902787127, 636.2460215985637, 636.2460215985637, 524.325280717991, 524.325280717991, 419.583126448145, 419.583126448145]


In [18]:
lista4.sort()
s = (lista4[0] + lista4[1] + lista4[2]) / 3.0
print(s)

454.4971778714269


In [19]:
lista5 = []
i = s
while i <=  s + 0.1 * s:
    dbscan = DBSCAN(eps = i)
    dbscan.fit(X)
    lista5.append(len(set(dbscan.labels_)))
    i += i * 0.04

In [20]:
print(lista5)

[23, 23, 17]


In [21]:
file = open("dbscan_len.pkl","wb")
pickle.dump(lista5, file)

In [22]:
file = open("dbscan_len.pkl","rb")
a = pickle.load(file)
file.close()
print(a)

[23, 23, 17]
